from pathlib import Path
from pptx import Presentation
from pptx.util import Inches, Pt
from jinja2 import Template
from ..config import OUTPUTS_DIR

class CreativeAgent:
    def create_banner(self, title: str, subtitle: str = "", theme: str = "olive") -> dict:
        html = self._banner_html(title, subtitle, theme)
        path = OUTPUTS_DIR / f"banner_{self._safe(title)}.html"
        path.write_text(html, encoding="utf-8")
        return {"file": str(path), "html": html, "note": "Abra o HTML no navegador e exporte/print como imagem se desejar."}

    def create_canvas(self, title: str, blocks: list[dict], theme: str = "clean") -> dict:
        tpl = Template("""
<!doctype html><html lang='pt-br'><head><meta charset='utf-8'><meta name='viewport' content='width=device-width,initial-scale=1'>
<title>{{title}}</title><style>
body{font-family:Arial,sans-serif;background:#f6f5ef;color:#222;margin:0;padding:32px}.page{max-width:1100px;margin:auto;background:white;border-radius:22px;padding:32px;box-shadow:0 20px 50px #0002}h1{color:#6B7A2D}.block{border-left:5px solid #C9A646;margin:18px 0;padding:16px;background:#fafafa;border-radius:12px}.muted{color:#777}
</style></head><body><main class='page'><h1>{{title}}</h1>{% for b in blocks %}<section class='block'><h2>{{b.title}}</h2><p>{{b.text}}</p></section>{% endfor %}<p class='muted'>Generated by Skatlaz Studies MCP</p></main></body></html>
""")
        html = tpl.render(title=title, blocks=blocks)
        path = OUTPUTS_DIR / f"canvas_{self._safe(title)}.html"
        path.write_text(html, encoding="utf-8")
        return {"file": str(path), "html": html}

    def create_presentation(self, title: str, slides: list[str], subtitle: str = "Skatlaz Studies MCP") -> dict:
        prs = Presentation()
        slide = prs.slides.add_slide(prs.slide_layouts[0])
        slide.shapes.title.text = title
        slide.placeholders[1].text = subtitle
        for item in slides:
            s = prs.slides.add_slide(prs.slide_layouts[1])
            s.shapes.title.text = str(item)[:80]
            body = s.placeholders[1]
            body.text = f"Conteúdo sugerido para: {item}\n\n• Conceito principal\n• Exemplo prático\n• Exercício ou reflexão"
        path = OUTPUTS_DIR / f"presentation_{self._safe(title)}.pptx"
        prs.save(path)
        return {"file": str(path), "slides": len(slides) + 1}

    def image_prompt(self, subject: str, style: str = "Van Gogh", format: str = "banner") -> dict:
        prompt = f"{subject}, style {style}, high quality, clean composition, {format}, Skatlaz brand, olive white brown silver palette"
        return {"prompt": prompt, "engine_hint": "Use Flux, Image Z-Turbo, Stable Diffusion, DALL-E or local image connector."}

    def _banner_html(self, title: str, subtitle: str, theme: str) -> str:
        return f"""<!doctype html><html><head><meta charset='utf-8'><style>
body{{margin:0;font-family:Arial,sans-serif;background:#f4f1e8}}.banner{{width:1200px;height:630px;display:flex;flex-direction:column;justify-content:center;padding:70px;box-sizing:border-box;background:linear-gradient(135deg,#ffffff,#e9e4d5);border:18px solid #6B7A2D}}h1{{font-size:72px;color:#6B7A2D;margin:0 0 24px}}p{{font-size:32px;color:#7a5a24;margin:0}}.tag{{position:absolute;bottom:40px;right:60px;color:#888;font-size:22px}}
</style></head><body><section class='banner'><h1>{title}</h1><p>{subtitle}</p><div class='tag'>Skatlaz Studies MCP</div></section></body></html>"""

    def _safe(self, s: str) -> str:
        return "".join(c if c.isalnum() else "_" for c in s.lower())[:80]
